version: 2.1
orbs:
  # orgs contain basc recipes and reproducible actions (install node, aws, etc.)
  node: circleci/node@4.1.0
  aws-cli: circleci/aws-cli@1.3.1
  eb: circleci/aws-elastic-beanstalk@1.0.0
  # different jobs are called later in the workflows sections
jobs:
  build:
    docker:
      # the base image can run most needed actions with orbs
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      - eb/setup
      # install dependencies in the apps
      - run:
          name: Frontend Install
          command: |
            npm run frontend:install
      - run:
          name: Backendend Install
          command: |
            npm run backend:install
      # Build Front-End and Back-End
      - run:
          name: Frontend Build
          command: |
            npm run frontend:build
      - run:
          name: Backendend Build
          command: |
            npm run backend:build
      # Deploy Front-End and Back-End
      - run:
          name: Deploy Frontend
          command: |
            echo "deploying frontend"
            aws s3 sync ./udagram-frontend/www s3://udagram-backend-5655662366326
      - run:
          name: Deploy Backend
          command: |
            echo "Deploying api to ebs."
            cd ./udagram-api
            eb deploy Udagramapp-env
            eb setenv -e Udagramapp-env AWS_ACCESS_KEY=$AWS_ACCESS_KEY AWS_BUCKET=$AWS_BUCKET AWS_PROFILE=$AWS_PROFILE AWS_REGION=$AWS_REGION AWS_SECRET=$AWS_SECRET JWT_SECRET=$JWT_SECRET PORT=$PORT POSTGRES_DB=$POSTGRES_DB POSTGRES_HOST=$POSTGRES_HOST POSTGRES_PASSWORD=$POSTGRES_PASSWORD POSTGRES_PORT=$POSTGRES_PORT POSTGRES_USERNAME=$POSTGRES_USERNAME URL=$URL
workflows:
  -deb_test2_21:
    jobs:
      - build:
          filters:
            branches:
              only: main